target 'TFUtils', :exclusive => true do
  pod 'TFLogger', :path => "../../TFLogger/TFLogger.podspec"
  pod "TFUtils", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TFUtils", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
