target 'TFUtils', :exclusive => true do
  pod "TFLogger", :git => "https://github.com/TriforkKRK/TFLogger.git"
  #pod 'TFLogger', :path => "../../TFLogger"
  pod "TFUtils", :path => "../"

    post_install do |installer_representation|
        installer_representation.project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NSLOG_TO_TFLOGGER_ENABLED=1'
            end
        end
    end
end

target 'Tests', :exclusive => true do
  pod "TFUtils", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
